apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wap-ingress
  namespace: wap
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: kubernetes.docker.internal
      http:
        paths:
          - path: /api/(.*)
            backend:
              serviceName: api
              servicePort: 8080
          - path: /admin/(.*)
            backend:
              serviceName: admin
              servicePort: 8080
          - path: /(.*)
            backend:
              serviceName: game
              servicePort: 8080
          - path: /asset/(.*)
            backend:
              serviceName: game
              servicePort: 8080
